### ISSUE TITLE
Incorrect errors detected in yaml manifests

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/cloud-code-vscode#101]
**Environment**:
Extension version: 0.0.8
VSCode version: 1.33.1
OS: linux

**Description**:
I have a K8s yaml manifest for a variety of k8s objects, including CRDs.
The Cloud Code extension detects a spec block and incorrectly reports "Missing template" error.
It seems to have assumed my yaml manifest is that of a Deployment object, rather than looking for required fields based on the kind specified in the manifest.

**Repro step**:
Open a yaml file for a CRD. In my case, I had several CRDs in the same yaml file separated with the "---" separator. Here is an example of the CRD. The spec field is flagged:

```
kind: MyResource
apiVersion: myapi/v1
metadata:
  name: res1
spec:
  xyz: 123
```
