### ISSUE TITLE
[Helm Support] Debugging not working for "Run/Debug on Kubernetes" command when helm is used for deployment

### ISSUE THREAD

**Issue by sharmajyo** [GoogleCloudPlatform/cloud-code-vscode#268]
Environment:
Extension version: 1.4.1
VSCode version: 1.47.2
OS: MacOS Catalina

Description:
When using the "Run/Debug on Kubernetes" command (via launch), debugging doesn't work for me if skaffold.yaml _deploy_ option is _helm_.

I tested this for cloud code's node hello-world [sample](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/nodejs/nodejs-hello-world), debugging works fine when skaffold.yaml _deploy_ option is _kubectl_ but modifying that to use helm stopped debugging.

Repro step:

Clone the cloud-code-samples repository.
Open one of the nodejs samples (I used nodejs-hello-world) in vscode.
Run the command "Run/Debug on Kubernetes"
Debugger gets attached and works fine.
Modify skaffold.yaml to use helm for deploy and create a helm-chart folder for required deployment and service templates
this is how my deploy section looks in skaffold.yaml
```
deploy:
  helm:
    releases:
    - name: hello-world
      chartPath: helm-chart
      values:
        image: nodejs-hello-world
      imageStrategy:
        helm: {}
```
Run the command "Run/Debug on Kubernetes"
Debugger doesn't get attached
