### ISSUE TITLE
yaml errors in not k8s yaml documents

### ISSUE THREAD

**Issue by BjMrq** [GoogleCloudPlatform/cloud-code-vscode#269]
**Environment**:

Extension version:
VSCode version: 1.47.2
OS: Ubuntu 20

**Description**:
Hello, the intellissence of the extension is great, but when in a writting non k8s yaml document I get errors.
Let say I am writing a AWS SAM serverless document i will get errors using !Ref for exemple.

**Repro step**:
- Open vs code with extension cloud run enable 
- create a yaml file (like template.yaml)
- paste the following 

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Hello Word Sam"

Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.x
    Timeout: 5
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
```
