### ISSUE TITLE
Specify image tag via extension

### ISSUE THREAD

**Issue by mattcopas** [GoogleCloudPlatform/cloud-code-vscode#335]
**Use case**
What are you trying to do that our extension doesn't let you?

Effectively I want to specify the `skaffold --tag` parameter via the extension (ie override the Docker image tag). In my organisation, it's very useful to have each developer use their own unique Docker image tags, so that I can easily delete my own images from the registry - e.g. all images I push have the tag `:mattcopas`.

**Feature**
What would help?

There are a couple of ways I can think to do this:

Add a `tag` property to the launch configuration options. This property would be the equivalent of `--tag` when running say, `skaffold dev --tag mattcopas`.

or maybe

Add an `env` property to the launch configuration options, e.g.: `"env: {"TAG": "mattcopas"}`

In this example. `TAG` would become an environment variable, and be used by Skaffold in:

```yaml
build:
  tagPolicy:
    envTemplate:
      template: "{{ .TAG }}"
```

**Comment by mattcopas** [comment]
A hacky workaround in the meantime would be to use:

```yaml
build:
  tagPolicy:
    gitCommit:
      prefix: mattcopas
```

However, this would mean each developer having to edit the `skaffold.yaml` him/herself - certainly not ideal as this file is in source control.
