### ISSUE TITLE
YAML outline incorrectly handles arrays of objects

### ISSUE THREAD

**Issue by pbavinck** [GoogleCloudPlatform/cloud-code-vscode#339]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.7
VSCode version: 1.51.1
OS: OSX 10.15.7

**Description**:
YAML outline is incorrect.

**Repro step**:
Use the following correct yaml definition:
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: myTaskRun
spec:
  serviceAccountName: ""
  taskRef:
    name: myTask
  params:
    - name: myMessage
      value: "This is a param"
    - name: myMessage
      value: "This is another param"
```

Expected is that the array of 2 objects containing the params information (2 attributes) are properly shown as 2 individual array elements. 
![image](https://user-images.githubusercontent.com/4839523/100436701-01523f00-30a0-11eb-9e10-9c2b4cc3b316.png)

Instead the "internal" attributes of the param objects are shown as array elements (4 in total).
![image](https://user-images.githubusercontent.com/4839523/100436725-0911e380-30a0-11eb-94fe-37d87d01e370.png)
