### ISSUE TITLE
parsing skaffold config: unknown api version: "skaffold/v2beta11"

### ISSUE THREAD

**Issue by dsaydon90** [GoogleCloudPlatform/cloud-code-vscode#376]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: v1.8.0
VSCode version: 1.52.1
OS: ubuntu 20
Skaffold: v1.19.0

**Description**:
```
Starting to debug the app using configuration 'Kubernetes: Run/Debug' from .vscode/launch.json...
To view more detailed logs, go to Output channel : "Kubernetes: Run/Debug - Detailed"
Dependency check started
Dependency check succeeded
parsing skaffold config: unknown api version: "skaffold/v2beta11"
Exited with code 1.
Cleaning up...
Finished clean up.
```

**Repro step**:
create project with the structure
```
project
|_.vscode
  |_launch.json
|_ application
  |_Dockerfile
  |_ <node js code files..>
|_kuerbenetes
  |_skaffold.yaml
  |_ <helm chart of the project>
```
create `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Kubernetes: Run/Debug",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/Kubernetes/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true
        }
    ]
}
```
create `skaffold.yaml`:
```
apiVersion: skaffold/v2beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
  artifacts:
  - image: project
    context: "../Application"
    docker:
      dockerfile: "Dockerfile"
      buildArgs:
        FOO: "{{.BAR}}"
    sync:
      infer:
      - '**/*'
deploy:
  kubeContext: minikube
  helm:
    flags:
      upgrade: ['--install']  
    releases:
    - name: project
      chartPath: project
      namespace: local
      valuesFiles:
      - "project/dev-values.yaml"
      wait: true
      upgradeOnChange: true
      artifactOverrides:
        image: project
      setValues:
        image.pullPolicy: "IfNotPresent"
```
