### ISSUE TITLE
ability to change working directory (cwd)

### ISSUE THREAD

**Issue by dsaydon90** [GoogleCloudPlatform/cloud-code-vscode#377]
**Use case**
I have the following project structure under my `home` dir (`/home/user/project`)
```
project
|_.vscode
  |_launch.json
|_ Application
  |_Dockerfile
  |_ <node js code files..>
|_Kuerbenetes
  |_skaffold.yaml
  |_ <helm chart of the project>
```
my `skaffold.yaml`
```
apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
  artifacts:
  - image: project
    context: "../Application"
    docker:
      dockerfile: "Dockerfile"
      buildArgs:
        FOO: "{{.BAR}}"
    sync:
      infer:
      - '**/*'
deploy:
  kubeContext: minikube
  helm:
    flags:
      upgrade: ['--install']  
    releases:
    - name: project
      chartPath: project
      namespace: local
      valuesFiles:
      - "project/dev-values.yaml"
      wait: true
      upgradeOnChange: true
      artifactOverrides:
        image: project
      setValues:
        image.pullPolicy: "IfNotPresent"
```
my `launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Kubernetes: Run/Debug",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/Kubernetes/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true
        }
    ]
}
```
When I'm running the debug I'm getting the following error:
```
Starting to debug the app using configuration 'Kubernetes: Run/Debug' from .vscode/launch.json...
To view more detailed logs, go to Output channel : "Kubernetes: Run/Debug - Detailed"
Dependency check started
Dependency check succeeded
Update initiated
Update failed with error code DEVINIT_REGISTER_BUILD_DEPS
watching files for artifact "project": listing files: unable to evaluate build args: reading dockerfile: open /home/user/Application/Dockerfile: no such file or directory
```
Well, the correct path is `/home/user/project/Application/Dockerfile` and not `/home/user/Application/Dockerfile:`

**Feature**
add the ability to change the cwd (working directory)

Some note:
it might be related to the relative path under `context` that I have set in my `skaffold.yaml`:  `context: "../Application"` ?
so the evaluation of the `../Application` instead of using the full path of the `${workspaceFolder}/Kubernetes/skaffold.yaml` it might uses to evaluate the relative path with `${workspaceFolder}`

Environment:
(Hint: "Report Extension Issue on Github" command will fill these out for you.)
Extension version: v1.8.0
VSCode version: 1.52.1
OS: ubuntu 20
Skaffold: v1.19.0
