### ISSUE TITLE
ability to pass environment variables to the skaffold.yaml

### ISSUE THREAD

**Issue by dsaydon90** [GoogleCloudPlatform/cloud-code-vscode#378]
**Use case**

I'm working with `buildArgs` in my `skaffold.yaml` in order to pass argument to my `docker build`. The thing is that I'm using the `skaffold` syntax to add values from environment variables: `{{.ENV}}`

my `skaffold.yaml`

```
apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    useBuildkit: true
    push: false
  artifacts:
  - image: project
    context: "../Application"
    docker:
      dockerfile: "Dockerfile"
      buildArgs:
        FOO: "{{.BAR}}"
    sync:
      infer:
      - '**/*'
...
```
**Feature**
add the ability to create env vars so the `skaffold` will be able to use them while the evaluation
