### ISSUE TITLE
Undefined frontend-external

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#39]
Hello,

After a Code-deploy I get the following error:

```
Publicly exposed endpoints in the application:
frontend-external: http://undefined:4000
```

Here are the source I use

```yaml
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 8080
          image: sieben/backend
```

```yaml
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: backend-internal
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - 
    name: http
    port: 4001
    targetPort: 8080
```

```yaml
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 8080
          image: sieben/frontend
          env:
            - name: BACKEND_SERVICE_ADDR
              value: 'backend-internal:4001'
```

```yaml
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - 
    name: http
    port: 4000
    targetPort: 8080
```
