### ISSUE TITLE
[Feature] Unable to access Cloud Code via local IP

### ISSUE THREAD

**Issue by stx** [GoogleCloudPlatform/cloud-code-vscode#444]
Cloud Code only appears to bind on localhost, preventing access via local IP (and, say, your phone, or any other debugging or development device.)

Is there a way to fix this or have it bind on 0.0.0.0?

**Comment by sivakku** [comment]
Ok, thanks for the feedback, you would need to add address field in the skaffold.yaml  for this to configure to any other host IP as well.

https://skaffold.dev/docs/pipeline-stages/port-forwarding/

```
portForward:
- resourceType: deployment
  resourceName: myDep
  namespace: mynamespace
  port: 8080
  **address: 0.0.0.0**
  localPort: 9000
```
