### ISSUE TITLE
Question: Creating deployment profile from scratch

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [GoogleCloudPlatform/cloud-code-vscode#475]
From what I understand going through [this](https://www.youtube.com/watch?v=62GLbBDLiPE&t=643s) presentation, there is an option to create a so called Deployment Profile directly via Cloud Code's available commands.

(screenshot below is from the presentation)

![Screenshot 2021-09-21 at 9 19 07 PM](https://user-images.githubusercontent.com/50835081/134225868-ed32cff9-7f3f-4744-afa8-0b921cd534c0.png)

If I am not wrong, the tool used under the hood is `skaffold`.

I could manually create myself the corresponding `skaffold.yaml`, however it would be ideal to have the process managed through Cloud Code and not decoupled (otherwise I assume I may end up running `skaffold run` etc commands my self, which I assume defeats the purpose of CloudCode

I see there is no plain `Deploy` option now in Cloud Code's commands (screenshot below is from my VSCode instance) but rather only an option for Cloud Run deploy.

Has the functionality been deprecated?

Is there a way to reproduce this behaviour and go through a guided process of Deployment Profile (a.k.a. `skaffold.yaml`) creation?

![Screenshot 2021-09-21 at 9 20 45 PM](https://user-images.githubusercontent.com/50835081/134226058-ab6b0893-1e99-4ac7-a176-04e71c68a040.png)

fwiw this is more or less where I want to be:

```
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: something
build:
  local:
    push: false
  artifacts:
  - image: myimage
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: ingestion-server
        remoteChart: https://something
  kubectl:
    manifests:
    - k8s/*
```
