### ISSUE TITLE
[Feature] Cloud code HelmRelease schema not known

### ISSUE THREAD

**Issue by brodowskid** [GoogleCloudPlatform/cloud-code-vscode#491]
**Version information**

Cloud Code Extension version:

Version v1.15.1

VSCode version:

1.61.2
OS:
Archlinux

**Problem**

This apiversion or kind does not reference a schema known by Cloud Code. Please ensure you are using valid apiversion and kind.

simple yaml file snippet.
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      # chart_version_prometheus defined in gitops/clusters/dev/apps.yaml resp. gitops/clusters/prod/apps.yaml
      version: 
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m0s
...

```
