### ISSUE TITLE
Cloud Code doesn't detect CRDs in cluster for authoring assist

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleCloudPlatform/cloud-code-vscode#533]
Cloud code is not detecting CRDs in the cluster for authoring assist.

Steps to reproduce:

```
kind create cluster
```

```
cat <<EOF >crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.custom.io
spec:
  group: custom.io
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: A sample CRD
        properties:
          apiVersion:
            description: 'APIVersion'
            type: string
          kind:
            description: 'Kind'
            type: string
          metadata:
            type: object
          spec:
            description: The spec for the CRD
            properties:
              name:
                description: Name
                type: string
            required:
            - name
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
EOF
```

```
kubectl apply -f crd.yaml
```

The CRD shows up in the CloudCode-Kubernetes dropdown but the IDE is not recognizing it.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/58999035/154826808-3b8b2ed3-9df3-497b-bd28-745bd95bd3c4.png">

On the other hand it is working if I point to the crd.yaml from settings.json. But I want it to be directly detected from the cluster without needing additional steps.

cc @uruddarraju
