### ISSUE TITLE
Extension 'Cloud Code' is configured as formatter but it cannot format 'YAML' files

### ISSUE THREAD

**Issue by inostia** [GoogleCloudPlatform/cloud-code-vscode#587]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 387.0.0
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2

Extension version: 1.18.2
VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (1.39GB free)|
|Process Argv|--crash-reporter-id 7886eff9-828c-4d82-9b6d-e59f094d5a02|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

*Description*
Trying to format YAML files in VSCode results in the error "Extension 'Cloud Code' is configured as formatter but it cannot format 'YAML' files". Sometimes, this error is seen alongside another error "The YAML Server crashed 5 times, it will not be restarted" (see https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/553 for that issue, which has been closed although I am still seeing the error).

**Comment by inostia** [comment]
I have investigated a bit further and have pinned down that the problem line is `apiVersion: kustomize.config.k8s.io/v1beta1` in my `kustomization.yaml` file. If I remove this line, then reload my VSCode window, the YAML server starts and I can format again.

My YAML:

```yaml
# when I remove this line, the YAML formatter works:
apiVersion: kustomize.config.k8s.io/v1beta1 

bases:
  - ./..

resources:
  - cronJobs.yaml
  - deployments.yaml
  - ingress.yaml
  - namespace.yaml
  - services.yaml
```

I tested it again on another file and was able to reproduce the error by adding `apiVersion: kustomize.config.k8s.io/v1beta1` to another `kustomization.yaml` file that previously did not have an `apiVersion`.

**Comment by inostia** [comment]
After further investigation, I have discovered that I was missing the `kind: Kustomization` field in the YAML file. Adding that fixed the Cloud Code error:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./..

resources:
  - cronJobs.yaml
  - deployments.yaml
  - ingress.yaml
  - namespace.yaml
  - services.yaml

```

Still, it would have been nice to get a validation error inline with the YAML instead of just having the YAML server crash. If you feel this is not a bug, go ahead and close this issue.
