### ISSUE TITLE
fatal: can't parse kube config file

### ISSUE THREAD

**Issue by Yensan** [GoogleCloudPlatform/cloud-code-vscode#604]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 390.0.0
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2
I use 

Extension version: 1.18.3
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|24, 10, 5|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 200d6d43-dd99-4c72-8b3f-26bd8a33c531|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by Yensan** [comment]
more info :
`ms-kubernetes-tools.vscode-kubernetes-tools` and `mindaro.mindaro` config in `settings.json`, works very well. 
```json
    "vs-kubernetes": {
        "vs-kubernetes.kubectlVersioning": "user-provided",
        "vs-kubernetes.outputFormat": "yaml",
        "vs-kubernetes.kubeconfig": "/Users/XXX/.kube/config.suse",
    },
```

But, `googlecloudtools.c` failed.
```json
    "cloudcode.kubeconfigs": [
    {"configPath": "/Users/XXX/.kube/config.suse"},
    ],
```

`Main side bar > CLOUD CODE > KUBERNETS > minikube > mouse right key > Copy Value ` it parse the path, but can't connect to the cluster.  Some times failed to parse config file, sometimes failed to connect. It is confused.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ./susemini/ca.crt
    server: https://192.168.0.9:57302
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: ./susemini/client.crt
    client-key: ./susemini/client.key
```


https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/602   this bug, he said CPU exhausted, I met, I use ice  to cool my Mac. This bug page is VERY VERY VERY hard to edit.
