### ISSUE TITLE
`skaffold debug` doesn't work with python 3.11. Same works with 3.9, 3.10.

### ISSUE THREAD

**Issue by cheburakshu** [GoogleCloudPlatform/cloud-code-vscode#735]
**Environment**:
*Extension 'googlecloudtools.cloudcode' v1.21.2*

**Version information**

Cloud Code Extension version: v1.21.2

VSCode version: 1.74.2 (Universal)

OS: Darwin

Cloud SDK: 

Skaffold: v2.0.4

Kubectl:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k3s1", GitCommit:"0dc63334c0db3e7b99244427615e091909fc486e", GitTreeState:"clean", BuildDate:"2022-11-18T18:17:40Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Description**:
Debugger doesn't work with python 3.11. Same works with 3.9, 3.10.

Fails with traceback

```
      > [hello-python-67df8754f8-qvtc2 hello-python] time="2023-02-09T01:07:43Z" level=warning msg="Debugging support for Python 3.11 not found: may require manually installing \"debugpy\""

```

**Repro step**:

1. Create a new dir `/tmp/debugger`
2. Create dockerfile with contents

```
/tmp/debugger
⟩ cat Dockerfile.python 
FROM python:3.11.1-alpine3.17

CMD ["python3", "-c", "import time; print('hello'); time.sleep(3600)"]
```

3. Create skaffold.yaml with contents

```
/tmp/debugger
⟩ cat skaffold.yaml 
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hello
build:
  artifacts:
  - image: hello-python
    context: .
    docker:
      dockerfile: Dockerfile.python
  tagPolicy:
    customTemplate:
      template: "latest"
  local:
    push: false

manifests:
  rawYaml:
  - "*.yml"

deploy:
  kubectl:
    defaultNamespace: default
```

4. create a deployment manifest hello-python.yml

```
/tmp/debugger
⟩ cat hello-python.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: IfNotPresent
```

5. Deploy with skaffold and ensure the deployment is running

```
/tmp/debugger
⟩ skaffold run
Generating tags...
 - hello-python -> hello-python:latest
Checking cache...
 - hello-python: Found Locally
Starting test...
Tags used in deployment:
 - hello-python -> hello-python:d29c075b7cfc0032295d0a2661ddd594e8cf2403c8fb9adcbe7dffb2ebfbbb56
Starting deploy...
 - deployment.apps/hello-python created
Waiting for deployments to stabilize...
 - deployment/hello-python is ready.
Deployments stabilized in 2.2 seconds
You can also run [skaffold run --tail] to get the logs


/tmp/debugger
⟩ kubectl -n default get po
NAME                            READY   STATUS    RESTARTS   AGE
hello-python-559bbc98b7-kkg4p   1/1     Running   0          16s

/tmp/debugger
⟩ 
```

6. Cleanup the deployment

```
/tmp/debugger
⟩ skaffold delete
Cleaning up...
 - deployment.apps "hello-python" deleted

```

7. Run `skaffold debug`

```
/tmp/debugger
⟩ skaffold debug
Listing files to watch...
 - hello-python
Generating tags...
 - hello-python -> hello-python:latest
Checking cache...
 - hello-python: Found Locally
Tags used in deployment:
 - hello-python -> hello-python:d29c075b7cfc0032295d0a2661ddd594e8cf2403c8fb9adcbe7dffb2ebfbbb56
Starting deploy...
 - deployment.apps/hello-python created
Waiting for deployments to stabilize...
 - deployment/hello-python: waiting for init container install-python-debug-support to complete
    - pod/hello-python-67df8754f8-qvtc2: waiting for init container install-python-debug-support to complete
      > [hello-python-67df8754f8-qvtc2 install-python-debug-support] Installing runtime debugging support files in /dbg
 - deployment/hello-python: container hello-python terminated with exit code 1
    - pod/hello-python-67df8754f8-qvtc2: container hello-python terminated with exit code 1
      > [hello-python-67df8754f8-qvtc2 hello-python] time="2023-02-09T01:07:43Z" level=warning msg="Debugging support for Python 3.11 not found: may require manually installing \"debugpy\""
      > [hello-python-67df8754f8-qvtc2 hello-python] /usr/local/bin/python3: No module named debugpy
      > [hello-python-67df8754f8-qvtc2 hello-python] time="2023-02-09T01:07:43Z" level=fatal msg="error launching python debugging: exit status 1"
 - deployment/hello-python failed. Error: container hello-python terminated with exit code 1.
Cleaning up...
 - deployment.apps "hello-python" deleted
1/1 deployment(s) failed

/tmp/debugger
⟩ 
```

8. Change the dockerfile to use python 3.9.16 instead of python 3.11.1. The debugger should work now.

```
/tmp/debugger
⟩ cat Dockerfile.python 
FROM python:3.9.16-alpine3.17

CMD ["python3", "-c", "import time; print('hello'); time.sleep(3600)"]

```

10. Ensure debugger works with python 3.9.16

```
/tmp/debugger
⟩ skaffold debug
Listing files to watch...
 - hello-python
Generating tags...
 - hello-python -> hello-python:latest
Checking cache...
 - hello-python: Not found. Building
Starting build...
Building [hello-python]...
Target platforms: [linux/amd64]
#1 [internal] load build definition from Dockerfile.python
#1 sha256:1cf9007333f04548457bd4a2516997b94eeb8420469c7fd109a9e2fc5b3a7dd2
#1 transferring dockerfile: 186B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:1604cb6ca4154d62d4deceef301d83527ea170a4166f726f94ed2a33d9843aca
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9.16-alpine3.17
#3 sha256:ab166aa9aab82929f499f3d1bb4f97825db743ac69d70254b1d246278b1d1f5b
#3 DONE 0.9s

#4 [1/1] FROM docker.io/library/python:3.9.16-alpine3.17@sha256:932941963166bcd15c4e5f4126e916b8cc84452881ca5d7d007b9639ca9b1443
#4 sha256:264b8ab4ab74d15769755c7199b652fb8ba3235c19530204f649ffac9768ed9a
#4 CACHED

#5 exporting to image
#5 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#5 exporting layers done
#5 writing image sha256:5b425a270443283cf27342846812521724e8d819ef9e841dac80512abf1d809e done
#5 naming to docker.io/library/hello-python:latest done
#5 DONE 0.0s
Build [hello-python] succeeded
Tags used in deployment:
 - hello-python -> hello-python:5b425a270443283cf27342846812521724e8d819ef9e841dac80512abf1d809e
Starting deploy...
 - deployment.apps/hello-python created
Waiting for deployments to stabilize...
 - deployment/hello-python: waiting for init container install-python-debug-support to complete
    - pod/hello-python-58fb66d46b-tcpwv: waiting for init container install-python-debug-support to complete
      > [hello-python-58fb66d46b-tcpwv install-python-debug-support] Installing runtime debugging support files in /dbg
 - deployment/hello-python is ready.
Deployments stabilized in 8.177 seconds
Press Ctrl+C to exit
Not watching for changes...
[install-python-debug-support] Installing runtime debugging support files in /dbg
[install-python-debug-support] Installation complete
Port forwarding pod/hello-python-58fb66d46b-tcpwv in namespace default, remote port 5678 -> http://127.0.0.1:5678

```
