### ISSUE TITLE
"Problem loading reference" on resources

### ISSUE THREAD

**Issue by gugahoi** [GoogleCloudPlatform/cloud-code-vscode#90]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: 0.0.7
VSCode version: 1.33.1
OS: MacOS 10.14.3

**Description**:
Most of my resources show linting errors in the first character despite them being valid.
For example the simplest svc definition has an error:

```yaml
# svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  sessionAffinity: None
  type: NodePort
```
```
# error (red underline in first character)
Problems loading reference 'k8s://schema/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta': Unable to load schema from 'k8s://schema/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta': 
```

![image](https://user-images.githubusercontent.com/355877/56398633-d0d3dd80-628c-11e9-990e-db5658322dcf.png)

**Repro step**:

Happened right after istalling cloud code, not sure how to repoduce in other machines other than simply installing and creating a resource definition?
